name:                grpc-client
version:             0.1.0.0
github:              "githubuser/grpc-client"
license:             Apache-2
author:              "Nick Waywood, Allison Irvin"
maintainer:          "example@example.com"
copyright:           "2020 Nick Waywood"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/grpc-client#readme>

dependencies:
- base >= 4.7 && < 5
- grpc-haskell-core
- grpc-haskell
- proto3-suite
- proto3-wire
- vector
- bytestring
- text
- deepseq
- containers
- utf8-string

library:
  source-dirs: src

executables:
  grpc-client-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wincomplete-uni-patterns
    dependencies:
    - grpc-client

tests:
  grpc-client-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - grpc-client
